import { useState, useEffect, useCallback, useRef } from "react";
import { useAuth } from "../contexts/AuthContext";
import { useOnlineStatus } from "./useOnlineStatus";
import { offlineDb } from "../lib/offlineDb";
import { deleteLocalRow, upsertLocalRow } from "../lib/offlineStore";
import { supabase } from "../lib/offlineSync";
import type {
  JournalEntry,
  JournalPhoto,
  JournalLocation,
  Mood,
} from "../types";

export type GenerateJournalOptions = {
  date: string;
  photos?: JournalPhoto[];
  locations?: JournalLocation[];
  model?: "gemini" | "openai" | "anthropic";
};

export const moodOptions: {
  value: Mood;
  label: string;
  emoji: string;
  color: string;
}[] = [
  { value: "happy", label: "Happy", emoji: "😊", color: "text-yellow-500" },
  { value: "good", label: "Good", emoji: "🙂", color: "text-green-500" },
  { value: "neutral", label: "Neutral", emoji: "😐", color: "text-slate-500" },
  { value: "sad", label: "Sad", emoji: "😢", color: "text-blue-500" },
  { value: "stressed", label: "Stressed", emoji: "😫", color: "text-red-500" },
];

const toJournalEntry = (row: Record<string, unknown>): JournalEntry => ({
  id: row.id as string,
  entryDate: row.entry_date as string,
  title: (row.title as string) ?? "",
  content: (row.content as string) ?? "",
  mood: (row.mood as Mood) ?? "neutral",
  tags: (row.tags as string[]) ?? [],
  photos: (row.photos as JournalPhoto[]) ?? [],
  locationLog: (row.location_log as JournalLocation[]) ?? [],
  autoGenerated: (row.auto_generated as boolean) ?? false,
  createdAt: row.created_at as string | undefined,
  updatedAt: row.updated_at as string | undefined,
});

const toJournalRow = (entry: JournalEntry, userId: string) => ({
  id: entry.id,
  user_id: userId,
  entry_date: entry.entryDate,
  title: entry.title,
  content: entry.content,
  mood: entry.mood,
  tags: entry.tags,
  photos: entry.photos ?? [],
  location_log: entry.locationLog ?? [],
  auto_generated: entry.autoGenerated ?? false,
  created_at: entry.createdAt,
  updated_at: entry.updatedAt,
});

const generateUuid = () => {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID();
  }
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (char) => {
    const rand = (Math.random() * 16) | 0;
    const value = char === "x" ? rand : (rand & 0x3) | 0x8;
    return value.toString(16);
  });
};

export const useJournal = () => {
  const { user } = useAuth();
  const isOnline = useOnlineStatus();
  const [entries, setEntries] = useState<JournalEntry[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isSyncing, setIsSyncing] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  const useSupabase = isOnline && !!user;
  const saveTimeoutRef = useRef<{ [key: string]: NodeJS.Timeout }>({});

  // Fetch all entries
  const fetchData = useCallback(async () => {
    if (!user) {
      setEntries([]);
      setIsLoading(false);
      return;
    }

    try {
      setIsSyncing(true);
      let rows: unknown[] = [];

      // If online, fetch from Supabase first
      if (isOnline && supabase) {
        try {
          const { data } = await supabase
            .from("journal_entries")
            .select("*")
            .eq("user_id", user.id);

          if (data) {
            rows = data;
            await offlineDb.journal_entries.bulkPut(
              data as Record<string, unknown>[],
            );
          }
        } catch (err) {
          console.error(
            "Failed to fetch from Supabase, using local data:",
            err,
          );
          // Fall through to local DB
        }
      }

      // If offline or Supabase failed, use local DB
      if (rows.length === 0) {
        rows = await offlineDb.journal_entries
          .where("user_id")
          .equals(user.id)
          .toArray();
      }

      const normalized = rows
        .map((row) => toJournalEntry(row as Record<string, unknown>))
        .sort((a, b) => b.entryDate.localeCompare(a.entryDate));

      setEntries(normalized);
    } catch (error) {
      console.error("Error fetching journal entries:", error);
    } finally {
      setIsLoading(false);
      setIsSyncing(false);
    }
  }, [user, isOnline]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  // Add entry
  const addEntry = async (date?: string) => {
    if (!user) return;

    try {
      setIsSyncing(true);
      const jstNow = new Date(Date.now() + 9 * 60 * 60 * 1000);
      const entryDate = date || jstNow.toISOString().split("T")[0];
      const now = new Date().toISOString();

      const newEntry: JournalEntry = {
        id: generateUuid(),
        entryDate,
        title: "",
        content: "",
        mood: "neutral",
        tags: [],
        createdAt: now,
        updatedAt: now,
      };

      await upsertLocalRow("journal_entries", toJournalRow(newEntry, user.id));
      setEntries((prev) => [newEntry, ...prev]);
      return newEntry;
    } catch (error) {
      console.error("Error adding journal entry:", error);
    } finally {
      setIsSyncing(false);
    }
  };

  // Update entry
  const updateEntry = (id: string, updates: Partial<JournalEntry>) => {
    if (!user) return;

    const updatedEntries = entries.map((e) =>
      e.id === id
        ? { ...e, ...updates, updatedAt: new Date().toISOString() }
        : e,
    );

    setEntries(updatedEntries);

    if (saveTimeoutRef.current[id]) {
      clearTimeout(saveTimeoutRef.current[id]);
    }

    saveTimeoutRef.current[id] = setTimeout(async () => {
      const updatedEntry = updatedEntries.find((entry) => entry.id === id);
      if (!updatedEntry) return;

      try {
        setIsSyncing(true);
        await upsertLocalRow(
          "journal_entries",
          toJournalRow(updatedEntry, user.id),
        );
      } catch (error) {
        console.error("Error updating journal entry:", error);
      } finally {
        setIsSyncing(false);
      }
    }, 500);
  };

  // Remove entry
  const removeEntry = async (id: string) => {
    if (!user) return;

    try {
      setIsSyncing(true);
      await deleteLocalRow("journal_entries", id);
      setEntries((prev) => prev.filter((e) => e.id !== id));
    } catch (error) {
      console.error("Error removing journal entry:", error);
    } finally {
      setIsSyncing(false);
    }
  };

  // Get entry by date
  const getEntryByDate = (date: string) => {
    return entries.find((e) => e.entryDate === date);
  };

  // Get entries by month
  const getEntriesByMonth = (year: number, month: number) => {
    const monthStr = `${year}-${String(month).padStart(2, "0")}`;
    return entries.filter((e) => e.entryDate.startsWith(monthStr));
  };

  // Get streak count (consecutive days with entries)
  const getStreak = () => {
    if (entries.length === 0) return 0;

    const sortedDates = entries
      .map((e) => e.entryDate)
      .sort((a, b) => b.localeCompare(a));

    const jstToday = new Date(Date.now() + 9 * 60 * 60 * 1000);
    let streak = 0;
    let currentDate = new Date(jstToday.getTime());

    for (const dateStr of sortedDates) {
      const expectedDate = currentDate.toISOString().split("T")[0];
      if (dateStr === expectedDate) {
        streak++;
        currentDate.setDate(currentDate.getDate() - 1);
      } else if (dateStr < expectedDate) {
        break;
      }
    }

    return streak;
  };

  // Restore state for undo/redo
  const restoreState = async (state: JournalEntry[]) => {
    if (!user) {
      setEntries(state);
      return;
    }

    setEntries(state);

    try {
      const currentRows = await offlineDb.journal_entries
        .where("user_id")
        .equals(user.id)
        .toArray();

      const nextIds = new Set(state.map((entry) => entry.id));

      for (const row of currentRows) {
        if (!nextIds.has(row.id as string)) {
          await deleteLocalRow("journal_entries", row.id as string);
        }
      }

      for (const entry of state) {
        await upsertLocalRow("journal_entries", toJournalRow(entry, user.id));
      }
    } catch (error) {
      console.error("Error restoring journal state:", error);
    }
  };

  // Generate journal entry via AI
  const generateEntry = async (options: GenerateJournalOptions) => {
    if (!user || !supabase) return;

    try {
      setIsGenerating(true);
      const { data, error } = await supabase.functions.invoke(
        "generate_journal",
        {
          body: {
            date: options.date,
            photos: options.photos ?? [],
            locations: options.locations ?? [],
            model: options.model ?? "gemini",
          },
        },
      );

      if (error) throw error;

      const newEntry: JournalEntry = {
        id: data.id,
        entryDate: data.entry_date,
        title: data.title,
        content: data.content,
        mood: data.mood,
        tags: ["auto-journal"],
        photos: data.photos ?? [],
        locationLog: data.location_log ?? [],
        autoGenerated: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };

      // Update local DB and state
      await upsertLocalRow("journal_entries", toJournalRow(newEntry, user.id));
      setEntries((prev) =>
        [newEntry, ...prev].sort((a, b) =>
          b.entryDate.localeCompare(a.entryDate),
        ),
      );

      return newEntry;
    } catch (error) {
      console.error("Error generating journal entry:", error);
      throw error;
    } finally {
      setIsGenerating(false);
    }
  };

  const refresh = useCallback(async () => {
    setIsSyncing(true);
    await fetchData();
    setIsSyncing(false);
  }, [fetchData]);

  return {
    entries,
    isLoading,
    isSyncing,
    isGenerating,
    useSupabase,
    addEntry,
    updateEntry,
    removeEntry,
    generateEntry,
    getEntryByDate,
    getEntriesByMonth,
    getStreak,
    refresh,
    restoreState,
  };
};
