import { useState, useMemo, useEffect, useCallback, useRef } from "react";
import {
  Plus,
  Trash2,
  Loader2,
  RefreshCw,
  BookOpen,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Calendar,
  Flame,
  Search,
  X,
  Sparkles,
  Bot,
  MapPin,
  ImageIcon,
} from "lucide-react";
import { useJournal, moodOptions } from "../hooks/useJournal";
import { useAuth } from "../contexts/AuthContext";
import { useUndoRedo } from "../contexts/UndoRedoContext";
import { Layout, ConfirmDialog } from "../components";
import { useUserSetting } from "../hooks/useUserSetting";
import type { JournalEntry, Mood } from "../types";

const formatDate = (dateStr: string) => {
  const date = new Date(dateStr);
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    weekday: "short",
  });
};

const formatDateShort = (dateStr: string) => {
  const date = new Date(dateStr);
  return date.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
  });
};

// Journal Entry Card Component
const JournalCard = ({
  entry,
  onUpdate,
  onDeleteClick,
}: {
  entry: JournalEntry;
  onUpdate: (id: string, updates: Partial<JournalEntry>) => void;
  onDeleteClick: (id: string) => void;
}) => {
  const [isExpanded, setIsExpanded] = useState(!entry.title && !entry.content);
  const moodOption =
    moodOptions.find((m) => m.value === entry.mood) || moodOptions[2];

  return (
    <div className="neu-card overflow-hidden">
      <div className="p-3 md:p-5">
        {/* Header row */}
        <div className="flex items-start gap-2 md:gap-3">
          <div className="bg-indigo-100 p-1.5 md:p-2 rounded-lg shrink-0">
            <BookOpen size={18} className="md:w-5 md:h-5 text-indigo-600" />
          </div>
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 flex-wrap mb-1">
              <span className="text-xs md:text-sm neu-text-secondary">
                {formatDate(entry.entryDate)}
              </span>
              {entry.autoGenerated && (
                <span className="inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded-full bg-violet-100 text-violet-600 text-[10px] font-medium">
                  <Bot size={10} />
                  AI
                </span>
              )}
              <button
                onClick={() => {
                  const currentIndex = moodOptions.findIndex(
                    (m) => m.value === entry.mood,
                  );
                  const nextIndex = (currentIndex + 1) % moodOptions.length;
                  onUpdate(entry.id, { mood: moodOptions[nextIndex].value });
                }}
                className="text-lg md:text-xl hover:scale-110 transition-transform"
                title={`Mood: ${moodOption.label}`}
              >
                {moodOption.emoji}
              </button>
            </div>
            {isExpanded ? (
              <textarea
                ref={(el) => {
                  if (el) {
                    el.style.height = "auto";
                    el.style.height = el.scrollHeight + "px";
                  }
                }}
                value={entry.title}
                onChange={(e) => onUpdate(entry.id, { title: e.target.value })}
                placeholder="Title..."
                className="w-full text-base md:text-lg font-semibold neu-text-primary bg-transparent border-none outline-none placeholder:neu-text-muted focus:ring-0 resize-none overflow-hidden"
                rows={1}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.nativeEvent.isComposing) {
                    e.preventDefault();
                    e.currentTarget.blur();
                  }
                }}
              />
            ) : (
              <input
                type="text"
                value={entry.title}
                onChange={(e) => onUpdate(entry.id, { title: e.target.value })}
                placeholder="Title..."
                className="w-full text-base md:text-lg font-semibold neu-text-primary bg-transparent border-none outline-none placeholder:neu-text-muted focus:ring-0"
              />
            )}

            {/* Summary when collapsed */}
            {!isExpanded && entry.content && (
              <p className="mt-1 text-xs md:text-sm neu-text-secondary line-clamp-2">
                {entry.content}
              </p>
            )}
          </div>
          <div className="flex items-center gap-1 shrink-0">
            <button
              onClick={() => setIsExpanded(!isExpanded)}
              className="p-1.5 md:p-2 neu-text-muted hover:neu-text-secondary hover:neu-pressed rounded-lg transition-colors"
              title={isExpanded ? "Collapse" : "Expand"}
            >
              {isExpanded ? (
                <ChevronUp size={16} className="md:w-[18px] md:h-[18px]" />
              ) : (
                <ChevronDown size={16} className="md:w-[18px] md:h-[18px]" />
              )}
            </button>
            <button
              onClick={() => onDeleteClick(entry.id)}
              className="p-1.5 md:p-2 neu-text-muted hover:text-red-500 hover:bg-red-50 rounded-lg transition-colors"
              title="Delete"
            >
              <Trash2 size={16} className="md:w-[18px] md:h-[18px]" />
            </button>
          </div>
        </div>

        {/* Expanded details - full width */}
        {isExpanded && (
          <div className="mt-3">
            <textarea
              value={entry.content}
              onChange={(e) => onUpdate(entry.id, { content: e.target.value })}
              placeholder="Write about your day..."
              rows={4}
              className="w-full text-sm neu-text-secondary neu-input rounded-lg px-3 py-2 resize-y min-h-[80px] md:min-h-[120px]"
            />

            {/* Photos */}
            {entry.photos && entry.photos.length > 0 && (
              <div className="mt-2 md:mt-3">
                <div className="flex items-center gap-1.5 mb-1.5">
                  <ImageIcon size={13} className="neu-text-muted" />
                  <span className="text-xs neu-text-secondary font-medium">
                    Photos
                  </span>
                </div>
                <div className="flex flex-wrap gap-2">
                  {entry.photos.map((photo, i) => (
                    <div key={i} className="relative group">
                      <img
                        src={photo.url}
                        alt={photo.description || "Photo"}
                        className="w-20 h-20 md:w-24 md:h-24 rounded-lg object-cover border border-slate-200"
                        loading="lazy"
                      />
                      {photo.description && (
                        <div className="absolute bottom-0 left-0 right-0 bg-black/50 text-white text-[10px] px-1 py-0.5 rounded-b-lg truncate opacity-0 group-hover:opacity-100 transition-opacity">
                          {photo.description}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Locations */}
            {entry.locationLog && entry.locationLog.length > 0 && (
              <div className="mt-2 md:mt-3">
                <div className="flex items-center gap-1.5 mb-1.5">
                  <MapPin size={13} className="neu-text-muted" />
                  <span className="text-xs neu-text-secondary font-medium">
                    Locations
                  </span>
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {entry.locationLog.map((loc, i) => (
                    <span
                      key={i}
                      className="inline-flex items-center gap-1 px-2 py-1 rounded-full bg-emerald-50 text-emerald-700 text-xs"
                    >
                      <MapPin size={11} />
                      {loc.name}
                      {loc.visited_at && (
                        <span className="text-emerald-500 text-[10px]">
                          {loc.visited_at}
                        </span>
                      )}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Mood selector */}
            <div className="mt-2 md:mt-3 flex items-center gap-2">
              <span className="text-xs neu-text-secondary">Mood:</span>
              <div className="flex gap-1">
                {moodOptions.map((mood) => (
                  <button
                    key={mood.value}
                    onClick={() =>
                      onUpdate(entry.id, { mood: mood.value as Mood })
                    }
                    className={`text-lg md:text-xl p-1 rounded-lg transition-all ${
                      entry.mood === mood.value
                        ? "neu-pressed scale-110"
                        : "opacity-50 hover:opacity-100"
                    }`}
                    title={mood.label}
                  >
                    {mood.emoji}
                  </button>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

// Mini Calendar Component
const MiniCalendar = ({
  entries,
  selectedDate,
  onSelectDate,
  currentMonth,
  onChangeMonth,
}: {
  entries: JournalEntry[];
  selectedDate: string | null;
  onSelectDate: (date: string) => void;
  currentMonth: Date;
  onChangeMonth: (date: Date) => void;
}) => {
  const year = currentMonth.getFullYear();
  const month = currentMonth.getMonth();

  const firstDay = new Date(year, month, 1);
  const lastDay = new Date(year, month + 1, 0);
  const startPadding = firstDay.getDay();

  const entryDates = new Set(entries.map((e) => e.entryDate));

  const days = [];
  for (let i = 0; i < startPadding; i++) {
    days.push(null);
  }
  for (let d = 1; d <= lastDay.getDate(); d++) {
    const dateStr = `${year}-${String(month + 1).padStart(2, "0")}-${String(d).padStart(2, "0")}`;
    days.push(dateStr);
  }

  const prevMonth = () => {
    onChangeMonth(new Date(year, month - 1, 1));
  };

  const nextMonth = () => {
    onChangeMonth(new Date(year, month + 1, 1));
  };

  return (
    <div className="neu-card p-4">
      <div className="flex items-center justify-between mb-3">
        <button onClick={prevMonth} className="p-1 hover:neu-pressed rounded">
          <ChevronLeft size={18} />
        </button>
        <span className="font-semibold neu-text-primary">
          {currentMonth.toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
          })}
        </span>
        <button onClick={nextMonth} className="p-1 hover:neu-pressed rounded">
          <ChevronRight size={18} />
        </button>
      </div>
      <div className="grid grid-cols-7 gap-1 text-center text-xs">
        {["S", "M", "T", "W", "T", "F", "S"].map((day, i) => (
          <div key={i} className="neu-text-muted py-1">
            {day}
          </div>
        ))}
        {days.map((dateStr, i) => {
          if (!dateStr) {
            return <div key={i} className="py-1"></div>;
          }
          const hasEntry = entryDates.has(dateStr);
          const isSelected = dateStr === selectedDate;
          const isToday = dateStr === new Date().toISOString().split("T")[0];
          const day = parseInt(dateStr.split("-")[2]);

          return (
            <button
              key={i}
              onClick={() => onSelectDate(dateStr)}
              className={`py-1 rounded-full text-sm transition-all ${
                isSelected
                  ? "bg-indigo-500 text-white"
                  : isToday
                    ? "bg-indigo-100 text-indigo-600 font-semibold"
                    : hasEntry
                      ? "bg-emerald-100 text-emerald-700 hover:bg-emerald-200"
                      : "hover:neu-pressed neu-text-secondary"
              }`}
            >
              {day}
            </button>
          );
        })}
      </div>
    </div>
  );
};

// Sidebar Section (Accordion) Component
const SidebarSection = ({
  title,
  children,
  defaultOpen = true,
  icon: Icon,
}: {
  title: string;
  children: React.ReactNode;
  defaultOpen?: boolean;
  icon?: React.ComponentType<{ size: number; className?: string }>;
}) => {
  const [isOpen, setIsOpen] = useState(defaultOpen);

  return (
    <div className="mb-4 neu-card overflow-hidden">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex items-center justify-between p-3 bg-slate-50 hover:neu-pressed transition-colors"
      >
        <div className="flex items-center gap-2 font-medium text-slate-700">
          {Icon && <Icon size={18} className="neu-text-secondary" />}
          <span>{title}</span>
        </div>
        {isOpen ? (
          <ChevronUp size={16} className="neu-text-muted" />
        ) : (
          <ChevronDown size={16} className="neu-text-muted" />
        )}
      </button>
      {isOpen && (
        <div className="p-3 border-t border-slate-200">{children}</div>
      )}
    </div>
  );
};

export const JournalPage = () => {
  useAuth();

  const {
    entries,
    isLoading,
    isSyncing,
    isGenerating,
    addEntry,
    updateEntry,
    removeEntry,
    generateEntry,
    getStreak,
    refresh,
    restoreState,
  } = useJournal();

  const { registerPage, unregisterPage, setCurrentPage, saveState } =
    useUndoRedo();
  const saveTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  // Set current page and register with undo/redo system
  useEffect(() => {
    setCurrentPage("journal");

    const getCurrentState = () => entries;
    const handleRestore = async (state: unknown) => {
      const s = state as JournalEntry[];
      if (restoreState) {
        await restoreState(s);
      }
    };

    registerPage("journal", getCurrentState, handleRestore);
    return () => unregisterPage("journal");
  }, [entries, registerPage, unregisterPage, restoreState, setCurrentPage]);

  // Save state to history on changes (debounced)
  const saveToHistory = useCallback(() => {
    if (saveTimeoutRef.current) {
      clearTimeout(saveTimeoutRef.current);
    }
    saveTimeoutRef.current = setTimeout(() => {
      saveState("journal");
    }, 500);
  }, [saveState]);

  // Wrapped handlers that save to history
  const addEntryWithHistory = useCallback(
    async (date?: string) => {
      const result = await addEntry(date);
      saveToHistory();
      return result;
    },
    [addEntry, saveToHistory],
  );

  const updateEntryWithHistory = useCallback(
    (id: string, updates: Partial<JournalEntry>) => {
      updateEntry(id, updates);
      saveToHistory();
    },
    [updateEntry, saveToHistory],
  );

  const removeEntryWithHistory = useCallback(
    async (id: string) => {
      await removeEntry(id);
      saveToHistory();
    },
    [removeEntry, saveToHistory],
  );

  const [currentMonth, setCurrentMonth] = useState(new Date());
  const [selectedDate, setSelectedDate] = useState<string | null>(null);
  const [deleteEntryId, setDeleteEntryId] = useState<string | null>(null);
  const { value: moodFilter, setValue: setMoodFilter } = useUserSetting<string>(
    "journal_filter_mood",
    "all",
  );
  const { value: journalSearch, setValue: setJournalSearch } =
    useUserSetting<string>("journal_filter_search", "");

  // ページネーション
  const ITEMS_PER_PAGE = 20;
  const [pageNumber, setPageNumber] = useState(1);

  // Filter entries by selected date, mood, and search text
  const filteredEntries = useMemo(() => {
    let result = entries;
    if (selectedDate) {
      result = result.filter((e) => e.entryDate === selectedDate);
    }
    if (moodFilter !== "all") {
      result = result.filter((e) => e.mood === moodFilter);
    }
    if (journalSearch.trim()) {
      const q = journalSearch.toLowerCase();
      result = result.filter(
        (e) =>
          e.title?.toLowerCase().includes(q) ||
          e.content?.toLowerCase().includes(q),
      );
    }
    return result;
  }, [entries, selectedDate, moodFilter, journalSearch]);

  // ページネーション計算
  const totalPages = Math.ceil(filteredEntries.length / ITEMS_PER_PAGE);
  const paginatedEntries = useMemo(() => {
    const startIndex = (pageNumber - 1) * ITEMS_PER_PAGE;
    return filteredEntries.slice(startIndex, startIndex + ITEMS_PER_PAGE);
  }, [filteredEntries, pageNumber]);

  // フィルター変更時にページをリセット
  useEffect(() => {
    setPageNumber(1);
  }, [selectedDate, moodFilter, journalSearch]);

  const [generateError, setGenerateError] = useState<string | null>(null);

  const handleAddEntry = async () => {
    const date = selectedDate || new Date().toISOString().split("T")[0];
    await addEntryWithHistory(date);
  };

  const handleGenerate = async () => {
    const jstNow = new Date(Date.now() + 9 * 60 * 60 * 1000);
    const date = selectedDate || jstNow.toISOString().split("T")[0];
    setGenerateError(null);
    try {
      await generateEntry({ date });
      saveToHistory();
    } catch (err) {
      setGenerateError(
        err instanceof Error ? err.message : "Failed to generate",
      );
    }
  };

  const headerLeft = (
    <button
      onClick={refresh}
      disabled={isSyncing}
      className="p-1.5 md:p-2 neu-text-secondary hover:neu-text-primary neu-btn rounded-lg transition-colors disabled:opacity-50"
      title="Refresh data"
    >
      <RefreshCw
        size={16}
        className={`md:w-[18px] md:h-[18px] ${isSyncing ? "animate-spin" : ""}`}
      />
    </button>
  );

  const headerCenter = (
    <div className="flex items-center gap-2">
      <button
        onClick={handleGenerate}
        disabled={isGenerating}
        className="flex items-center gap-1.5 md:gap-2 px-2.5 md:px-3 py-2 rounded-lg bg-violet-600 hover:bg-violet-500 text-white text-xs md:text-sm font-medium transition-all active:scale-95 shadow disabled:opacity-60"
        title="AIでジャーナルを自動生成"
      >
        {isGenerating ? (
          <Loader2 size={16} className="animate-spin" />
        ) : (
          <Sparkles size={16} />
        )}
        <span className="hidden sm:inline">
          {isGenerating ? "Generating..." : "AI Generate"}
        </span>
      </button>
      <button
        onClick={handleAddEntry}
        className="flex items-center gap-1.5 md:gap-2 px-2.5 md:px-3 py-2 rounded-lg bg-sky-600 hover:bg-sky-500 text-white text-xs md:text-sm font-medium transition-all active:scale-95 shadow"
      >
        <Plus size={16} />
        <span className="hidden sm:inline">Add Entry</span>
      </button>
    </div>
  );

  return (
    <Layout
      pageTitle="Journal"
      headerLeft={headerLeft}
      headerCenter={headerCenter}
    >
      {isLoading ? (
        <div className="flex-1 min-h-0 flex items-center justify-center">
          <Loader2 size={32} className="animate-spin neu-text-secondary" />
        </div>
      ) : (
        <div className="flex-1 min-h-0 overflow-auto mobile-scroll-pad md:overflow-hidden md:flex md:flex-row">
          {/* Sidebar - Calendar & Stats */}
          <div className="w-full md:w-80 md:shrink-0 p-3 md:p-4 neu-bg border-b md:border-b-0 md:border-r border-slate-200/50 md:overflow-auto md:shadow-[4px_0_6px_rgba(163,177,198,0.3)]">
            {/* Stats */}
            <SidebarSection
              title="Statistics"
              icon={Flame}
              defaultOpen={window.innerWidth >= 768}
            >
              <div className="grid grid-cols-2 gap-3">
                <div className="neu-flat rounded-xl p-3 text-center">
                  <div className="flex items-center justify-center gap-1 text-orange-500 mb-1">
                    <Flame size={18} />
                  </div>
                  <div className="text-xl font-bold neu-text-primary">
                    {getStreak()}
                  </div>
                  <div className="text-[10px] neu-text-secondary uppercase tracking-wide">
                    Streak
                  </div>
                </div>
                <div className="neu-flat rounded-xl p-3 text-center">
                  <div className="flex items-center justify-center gap-1 text-indigo-500 mb-1">
                    <Calendar size={18} />
                  </div>
                  <div className="text-xl font-bold neu-text-primary">
                    {entries.length}
                  </div>
                  <div className="text-[10px] neu-text-secondary uppercase tracking-wide">
                    Entries
                  </div>
                </div>
              </div>
            </SidebarSection>

            {/* Calendar */}
            <SidebarSection
              title="Calendar"
              icon={Calendar}
              defaultOpen={window.innerWidth >= 768}
            >
              <MiniCalendar
                entries={entries}
                selectedDate={selectedDate}
                onSelectDate={(date) => {
                  setSelectedDate((prev) => (prev === date ? null : date));
                }}
                currentMonth={currentMonth}
                onChangeMonth={setCurrentMonth}
              />
              {/* Clear filter button */}
              {selectedDate && (
                <button
                  onClick={() => setSelectedDate(null)}
                  className="w-full mt-3 px-4 py-2 text-sm neu-text-secondary bg-white border border-slate-200 rounded-lg hover:bg-slate-50 transition-colors"
                >
                  Show All Entries
                </button>
              )}
            </SidebarSection>
          </div>

          {/* Main Content */}
          <main className="md:flex-1 md:min-h-0 md:overflow-auto p-4 md:p-6 neu-bg">
            <div className="max-w-3xl mx-auto">
              {/* Generate status */}
              {isGenerating && (
                <div className="mb-4 flex items-center gap-2 px-4 py-3 rounded-lg bg-violet-50 border border-violet-200 text-violet-700 text-sm">
                  <Loader2 size={16} className="animate-spin" />
                  予定やタスクを元にジャーナルを生成しています...
                </div>
              )}
              {generateError && (
                <div className="mb-4 flex items-center justify-between px-4 py-3 rounded-lg bg-red-50 border border-red-200 text-red-700 text-sm">
                  <span>{generateError}</span>
                  <button
                    onClick={() => setGenerateError(null)}
                    className="p-1 hover:bg-red-100 rounded"
                  >
                    <X size={14} />
                  </button>
                </div>
              )}

              {/* Filters */}
              <div className="flex flex-nowrap md:flex-wrap items-center gap-2 mb-4 overflow-x-auto pb-1 md:pb-0 md:overflow-visible">
                <div className="relative">
                  <Search
                    size={14}
                    className="absolute left-2.5 top-1/2 -translate-y-1/2 neu-text-muted"
                  />
                  <input
                    type="text"
                    value={journalSearch}
                    onChange={(e) => setJournalSearch(e.target.value)}
                    placeholder="Search..."
                    className="w-32 sm:w-44 pl-8 pr-7 py-2 md:py-1.5 text-xs neu-input rounded-lg"
                  />
                  {journalSearch && (
                    <button
                      onClick={() => setJournalSearch("")}
                      className="absolute right-2 top-1/2 -translate-y-1/2 neu-text-muted hover:neu-text-secondary"
                    >
                      <X size={12} />
                    </button>
                  )}
                </div>
                {[
                  { value: "all", label: "All", emoji: "" },
                  ...moodOptions,
                ].map((m) => (
                  <button
                    key={m.value}
                    onClick={() =>
                      setMoodFilter(moodFilter === m.value ? "all" : m.value)
                    }
                    className={`flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-xs font-medium transition-all ${
                      moodFilter === m.value
                        ? "neu-chip-active text-sky-600"
                        : "neu-chip neu-text-secondary"
                    }`}
                  >
                    {"emoji" in m && m.emoji && (
                      <span className="text-sm">{m.emoji}</span>
                    )}
                    {m.label}
                  </button>
                ))}
              </div>

              {/* Header */}
              {selectedDate && (
                <div className="mb-4 flex items-center gap-2">
                  <h2 className="text-lg font-semibold neu-text-primary">
                    {formatDate(selectedDate)}
                  </h2>
                  <span className="text-sm neu-text-secondary">
                    ({filteredEntries.length}{" "}
                    {filteredEntries.length === 1 ? "entry" : "entries"})
                  </span>
                </div>
              )}

              {filteredEntries.length === 0 ? (
                <div className="text-center py-16 neu-bg">
                  <BookOpen size={48} className="mx-auto neu-text-muted mb-4" />
                  <p className="neu-text-secondary mb-4">
                    {selectedDate
                      ? `No entries for ${formatDateShort(selectedDate)}`
                      : "No journal entries yet"}
                  </p>
                  <button
                    onClick={handleAddEntry}
                    className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-sky-600 hover:bg-sky-500 text-white text-sm font-medium transition-all"
                  >
                    <Plus size={16} /> Write your first entry
                  </button>
                </div>
              ) : (
                <>
                  <div className="space-y-4">
                    {paginatedEntries.map((entry) => (
                      <JournalCard
                        key={entry.id}
                        entry={entry}
                        onUpdate={updateEntryWithHistory}
                        onDeleteClick={(id) => setDeleteEntryId(id)}
                      />
                    ))}
                  </div>

                  {/* Pagination */}
                  {totalPages > 1 && (
                    <div className="flex items-center justify-center gap-2 mt-6 pb-4">
                      <button
                        onClick={() =>
                          setPageNumber((prev) => Math.max(1, prev - 1))
                        }
                        disabled={pageNumber === 1}
                        className="p-2 rounded-lg border border-slate-200 hover:bg-slate-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                        title="Previous page"
                      >
                        <ChevronLeft size={18} />
                      </button>
                      <div className="flex items-center gap-1">
                        {Array.from({ length: totalPages }, (_, i) => i + 1)
                          .filter(
                            (page) =>
                              page === 1 ||
                              page === totalPages ||
                              Math.abs(page - pageNumber) <= 2,
                          )
                          .map((page, index, array) => (
                            <span key={page} className="flex items-center">
                              {index > 0 && array[index - 1] !== page - 1 && (
                                <span className="px-2 neu-text-muted">...</span>
                              )}
                              <button
                                onClick={() => setPageNumber(page)}
                                className={`w-10 h-10 md:w-8 md:h-8 rounded-lg text-sm font-medium transition-colors ${
                                  pageNumber === page
                                    ? "bg-indigo-500 text-white"
                                    : "hover:neu-pressed neu-text-secondary"
                                }`}
                              >
                                {page}
                              </button>
                            </span>
                          ))}
                      </div>
                      <button
                        onClick={() =>
                          setPageNumber((prev) =>
                            Math.min(totalPages, prev + 1),
                          )
                        }
                        disabled={pageNumber === totalPages}
                        className="p-2 rounded-lg border border-slate-200 hover:bg-slate-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                        title="Next page"
                      >
                        <ChevronRight size={18} />
                      </button>
                      <span className="ml-4 text-sm neu-text-secondary">
                        Showing {(pageNumber - 1) * ITEMS_PER_PAGE + 1}-
                        {Math.min(
                          pageNumber * ITEMS_PER_PAGE,
                          filteredEntries.length,
                        )}{" "}
                        of {filteredEntries.length}
                      </span>
                    </div>
                  )}
                </>
              )}
            </div>
          </main>

          {/* Delete Entry Confirmation */}
          <ConfirmDialog
            isOpen={deleteEntryId !== null}
            title="Delete Entry"
            message="Are you sure you want to delete this journal entry? This action cannot be undone."
            confirmLabel="Delete"
            onConfirm={async () => {
              if (deleteEntryId) {
                await removeEntryWithHistory(deleteEntryId);
                setDeleteEntryId(null);
              }
            }}
            onCancel={() => setDeleteEntryId(null)}
          />
        </div>
      )}
    </Layout>
  );
};
