-- Add columns for auto-journal generation feature
ALTER TABLE journal_entries
  ADD COLUMN IF NOT EXISTS photos jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS location_log jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS auto_generated boolean DEFAULT false;

-- photos: [{url, description, taken_at}]
-- location_log: [{name, lat, lng, visited_at}]

COMMENT ON COLUMN journal_entries.photos IS 'Array of photo objects: [{url, description, taken_at}]';
COMMENT ON COLUMN journal_entries.location_log IS 'Array of location objects: [{name, lat, lng, visited_at}]';
COMMENT ON COLUMN journal_entries.auto_generated IS 'Whether this entry was auto-generated by AI';
